config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :items

  root to: 'static_pages#index'
  get 'static_pages/about'


  resources :index
  resources :user

  resources :join_table_items_carts, only: [:create, :update, :destroy]
  resources :carts, except: [:index, :new, :edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user, optional: true
    has_many :join_table_items_carts, dependent: :nullify
    has_many :items, through: :join_table_items_carts
  end

app/models/item.rb
class Item < ApplicationRecord
    has_many :carts
    has_many :join_table_items_carts, dependent: :nullify
    has_many :orders, through: :join_table_order_items

end

app/models/join_table_items_cart.rb
class JoinTableItemsCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  after_create :order_send 

  def order_send 
    UserMailer.order_mail(self).deliver_now
    AdminMailer.order_mail(self).deliver_now
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

    has_one :cart

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

include ApplicationHelper
    after_action :create_cart_and_assign_to_current_user, only: [:create]
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

include CartsHelper
before_action :require_login
before_action :only_current_cart

  def show
    @items_in_cart = JoinTableItemsCart.where(cart_id:current_user.cart.id)
  end

  def create
  end

  def update
  end

  def destroy
  end






  
end

app/controllers/itembanners_controller.rb
# class ItemsbannersController < ApplicationController

#     def create
#         @item = Item.find(params[:item_id])
#         @item.itembanner.attach(params[:itembanner])
#         redirect_to(root_path)
#       end
# end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def index
      @items = Item.all
      @items = Item.all.sample
      @join_table_item_cart = JoinTableItemsCart.new
    end

    def show
      @item = Item.find(params[:id])
      @join_table_item_cart = JoinTableItemsCart.new

    end


    def add_to_card
      session[:cart] << params[:id]
      redirect_to root_path
    end


    def new
      @item = Item.new
    end


    def create
      @item = Item.new(title: params[:title],description: params[:description], image_url: params[:image_url])
      if @item.save
        redirect_to item_path(@item.id)
      else
        redirect_to root_path
      end
    end

    #private

    #def item_params
    # params.require(:item).permit(:title, :description, :price)
    #end







end

app/controllers/join_table_items_carts_controller.rb
class JoinTableItemsCartsController < ApplicationController
  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :authenticate_user!, only: [:secret]
  
    def index
        @items = Item.all
    end

    def show 
        @item = Item.find(params[:id])
    end




end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def create_cart_and_assign_to_current_user
        if current_user != nil && current_user.cart == nil
            cart = Cart.create(user: current_user)
        end
    end

end


##voir pour le helper ou helperSSSSS

app/helpers/carts_helper.rb
module CartsHelper

    private

    def require_login
        unless current_user != nil
            redirect_to new_user_session_path
        end
    end

    def only_current_cart
        if current_user != nil && current_user.cart.id != params[:id].to_i
            return redirect_to cart_path(current_user.cart.id)
        end
    end


end

app/helpers/join_table_items_carts_helper.rb
module JoinTableItemsCartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/show.html.erb
<br/>
<div class="container">
    <h1>Mon panier</h1>
    <br/>
    <br/>
        <div class="row">
            <div class="col-lg-8 col-md-8">
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Quantité</th>
                        <th scope="col">Nom de produit</th>
                        <th scope="col">Prix unitaire</th>
                        <th scope="col">Prix selon quantité</th>
                        <th scope="col"></th>
                        

                        </tr>

                        

                    </thead>
                    <tbody>
                        <% total_price = [] %>
                        <%  @items_in_cart.each do |item| %>
                            <tr>
                            <th scope="row"><%= item.quantity %></th>
                            <td><%= item.item.title %></td>
                            <td><%= item.item.price %>€</td>
                            <td><%= total_item = item.item.price*item.quantity.to_d %>€</td>
                            <% total_price << total_item %>
                            </tr>
                        <% end %>

                        
                         <tr>
                            <th scope="row"></th>
                            <td></td>
                            <td></td></td>
                            <td></td>
                            </tr>
                            <tr>
                            <th scope="row"></th>
                            <td></td>
                            <td class="font-weight-bold">Prix total:</td>
                            <td><%= total_price.inject(0){|sum,x| sum + x }%>€</td>
                            </tr>
                    </tbody>
                </table>
            </div>
        </div>
</div>
<br>
<center><button type="button" class="btn btn-primary">Passer la commande</button></center>
<br>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/items/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Chatonnerie</title>
</head>

  <body>

  	<h4>Créer ton annonce pour vendre ta photo de chat !</h5>

      <div class ='align-middle'>
      <div class="card mt-5 ml-5 mr-5 p-4">
      <div class="card-body">


        	<%= form_tag url_for(action: 'create'), method: "post" do %>

						<div class="form-group">
                  <p><%= label_tag 'Titre :' %></p>
                  <p><%= text_field_tag(:title) %></p>
						</div>

            <div class="form-group">
                  <p><%= label_tag 'Description :' %></p>
                  <p><%= text_field_tag(:description) %></p>
						</div>

            <div class="form-group">
                  <p><%= label_tag 'Prix :' %></p>
                  <p><%= text_field_tag(:price) %></p>
						</div>

            <div class="form-group">
                  <p><%= label_tag 'Image à vendre :' %></p>
                  <p><%= text_field_tag(:image_url) %></p>
						</div>

				    <%= submit_tag "Créer mon annonce" %>

          <% end %>
				</div>
			</div>
		</div>

  </body>
</html>

app/views/items/show.html.erb
<div class="row justify-content-center p-5">
  <div class="col-lg-4 col-md-6 ml-auto mr-auto shadow-lg p-3 mb-5 bg-body rounded border border-3">
    <div class="card shadow-lg p-3 mb-5 bg-body rounded border border-3">
        <div class="d-flex justify-content-between align-items-center ">
            <div class="mt-2">
                <h4 class="text-uppercase">
                  <p>
                    <%= @item.title %>
                  </p>
                  <p>
                    <%= @item.description %>
                  </p>
                </h4>
                <div class="mt-5">
                    <h1 class="main-heading mt-0"><%= @item.price %> €</h1>
                    <div class="d-flex flex-row user-ratings">
                        <div class="ratings"> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> <i class="fa fa-star"></i> </div>
                    </div>
                </div>
            </div>
            <div class="rounded mx-3"> <%= image_tag("cat.jpg", width:"200", :alt => "rss feed") %> </div>
        </div>



        <%= link_to "Ajouter au Panier", "join_table_items_carts#create" %>




    </div>
</div>
</div>

app/views/join_table_items_carts/create.html.erb
<h1>JoinTableItemsCarts#create</h1>
<p>Find me in app/views/join_table_items_carts/create.html.erb</p>

app/views/join_table_items_carts/destroy.html.erb
<h1>JoinTableItemsCarts#destroy</h1>
<p>Find me in app/views/join_table_items_carts/destroy.html.erb</p>

app/views/join_table_items_carts/update.html.erb
<h1>JoinTableItemsCarts#update</h1>
<p>Find me in app/views/join_table_items_carts/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>La Chatonnerie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

 <header class="p-3 bg-primary text-white">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="navbar-brand text-white" href="/">La Chatonnerie</a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="<%= new_item_path %>" class="nav-link px-2 text-white">Créer une annonce</a></li>
              <li><a href="/" class="nav-link px-2 text-white">Consulter les annonces</a></li>
              <li><a href="<%= static_pages_about_path %>" class="nav-link px-2 text-white">A propos de nous</a></li>
              
            </ul>

            <ul>
              <% if user_signed_in? %>

                <li>
                  <%= current_user.email %>
                </li>

                <li>
                  <%= link_to "Mon profil", user_path(current_user.id), {:style=>'color:#FFFFFF;'}%>
                </li>
                <li>
                <%= link_to "Mon panier", cart_path(current_user.cart.id), {:style=>'color:#FFFFFF;'}%>
              </li>
                <li>
                  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, style: 'color:#FFFFFF;' %>
                </li>

              <% else %>
              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="<%=new_user_session_path%>" class="btn btn me-2 text-white">Se connecter</a></li>
                <li><a href="<%=new_user_registration_path%>" class="btn btn-outline-light me-2">S inscrire</a></li>
              </ul>
              <% end %>
            </ul>

          </div>
        </div>
      </header>

  </head>

  <body>





      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


      <%= yield %>

  </body>


    <footer class="footer font-small">
    <div class="container-fluid text-center text-md-left">
    <div class="row">
      </div>
      <div class="footer-copyright text-center py-3">© 2022, La Chatonnerie
      </div>
  </footer>

</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Chatonnerie</title>
</head>

  <body>
      <div class="col-md-10 p-lg-1 mx-auto my-1">
      <div class="container-fluid">

        <center><h2 class="display-4 fw-normal" style="color: blue;"><strong>L'équipe de la Chatonnerie</strong></h2>
          <br>
          <h3 class="display- fw-normal" style="color: blue;">C'est une superbe équipe de 4 personnes suivant le bootcamp "The Hacking Project" qui ont décidé de lancer la Chatonnerie.</h3>
          <p>Pierre LEGROUX, Aurélie INGWEN, Niall BURDON & Bénédicte COULON</p></center>

      <div class ='align-middle'>
      <div class="card mt-5 ml-5 mr-5 p-4">
      <div class="card-body">
        <p class="card-title"><strong>La Chatonnerie te permet : </strong></p>
        <br>
        <p>- de publier une annonce pour vendre ta photo de chat</p>
        <p>- de passer une commande pour acheter une photo de chat</p>
      </div>
      </div>
      </div>

    </div></div>
</body>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Chatonnerie</title>

    <main class="bg-white py-5" style="background-image: url(https://maximumwallhd.com/wp-content/uploads/2017/04/wallpaper-image-chats-en-ete-11.jpg); background-size: 100%; background-position: center; background-repeat: no-repeat;">
    <div class="container px-5" >
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6"  >
                <div class="text-center my-5"  >
                   <br>

                        <br><br><br><br><br><br><br>
                    </div>
                        <br>
            <div>
                        <br>
                        <br>
                        <br>
                        <br>
                  </div>
            </div>
        </div>
    </div>
</main>


</head>
<body><br><br><br>
    <center>
    <h1 class="display-4 fw-bolder text-grey mb-2">La Chatonnerie 🐾 </h1><br>

    <p class="lead text-black-50 mb-4"><b>Le meilleur site en ligne pour obtenir les clichés de nos petits cats préférés 🥳</b></p>
    </center>
<br>
<div class="album py-5 bg-light">
<div class="container">
 <div class="row">
<% @items.each do |item| %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x100%]" style="height: 100%; width: 100%; display: block;" src="https://cdn.pixabay.com/photo/2019/05/08/21/21/cat-4189697_1280.jpg" data-holder-rendered="true">
                <div class="card-body">
                <h3 class="display-7"><%= item.title %></h3>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    <a class="btn btn-primary active mt-2 mb-4" href="<%=item_path(item.id)%>">Détails</a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
<% end %>

</body>
</html>

app/views/user/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Chatonnerie</title>

</head>

  <main>
    <h2>Mon profil :</h2>
    <div class ='align-middle'>
    <div class="card mt-5 ml-5 mr-5 p-4">
    <div class="card-body">

    <p class="card-title"><strong>Email: </strong> <%= @user.email %></p>

    <% if current_user.id == @user.id %>
    <%= link_to "Modifier mon mot de passe", edit_user_registration_path(@user.id) %>
    <% end %>

      <div class ='align-middle'>
      <div class="card mt-5 ml-5 mr-5 p-4">
      <div class="card-body">
        <p class="card-title"><strong>Commandes passées :</strong></p>
      </div>
      </div>
      </div>

      <div class ='align-middle'>
      <div class="card mt-5 ml-5 mr-5 p-4">
      <div class="card-body">
        <p class="card-title"><strong>Annonces parues :</strong></p>
      </div>
      </div>
      </div>
    </div>
    </div>
    </div>

  <main>
</html>